### ISSUE TITLE
 is not allowed by access-control-allow-origin

### ISSUE THREAD

**Issue by skating507** [karthikax/wpionic-material#1]
this code show: is not allowed by access-control-allow-origin.

**Comment by karthikax** [comment]
Access-Control-Allow-Origin is a security feature that the browsers implement. You can use [Ripple emulator](https://chrome.google.com/webstore/detail/ripple-emulator-beta/geelfhphabnejjhdalkjhgipohgpdnoc?hl=en) to overcome this security restriction.
