### ISSUE TITLE
How to get post id in ionic ?

### ISSUE THREAD

**Issue by VahidNZ** [karthikax/wpionic-material#2]
Hi everyone,
I want to know how to can add get_post ID in ionic my echo php as following :

echo get_post_meta($post->ID, 'tm_video_code', true);

Regards,
Vahid

**Comment by karthikax** [comment]
This can be better answered [here](https://github.com/WP-API/WP-API) as it is related to the customization of wordpress api.

**Comment by VahidNZ** [comment]
This address was not found, please check again
